# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-24 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='カテゴリ名')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wordmap.Category', verbose_name='親カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='単語名')),
                ('description', models.TextField(verbose_name='説明')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='最終更新日')),
                ('category', models.ManyToManyField(to='wordmap.Category', verbose_name='カテゴリ')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_words', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('last_editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_edited_words', to=settings.AUTH_USER_MODEL, verbose_name='最終更新者')),
            ],
        ),
    ]
